language: php

sudo: false

matrix:
    fast_finish: true
    include:
#        - php: 7.0
#        - php: 7.1
#        - php: 7.0
#          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 7.0
          env: SYMFONY_VERSION="~3.2@dev" COMPOSER_FLAGS="--prefer-stable" MINIMUM_STABILITY="dev"

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - |
      if [ $TRAVIS_TAG ]; then
          # for tag building for release we don't need to collect code coverage, let us turn off xdebug completely
          phpenv config-rm xdebug.ini || return 0
      else
          # for regular build we care about collecting code coverage, let us turn off xdebug only for installation part
          mv $HOME/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini $HOME/xdebug.ini || return 0
      fi
    - composer self-update
    # When the minimum requirement is changed update composer.
    - 'if [ "$MINIMUM_STABILITY" != "" ]; then perl -pi -e "s/^}$/,\"minimum-stability\":\"${MINIMUM_STABILITY}\"}/" composer.json; fi'
    - 'if [ "$SYMFONY_VERSION" != "" ]; then sed -i "s/\"symfony\/\([^\"]*\)\": \"[^\"]*\"/\"symfony\/\1\": \"$SYMFONY_VERSION\"/g" composer.json; fi'
    - cat composer.json

install:
    - travis_retry composer update $COMPOSER_FLAGS --no-interaction

script:
    - cp $HOME/xdebug.ini $HOME/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || return 0
    - vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_success:
    - php vendor/bin/coveralls -v
